### ISSUE TITLE
Corrupted mmseqs_cluster output

### ISSUE THREAD

**Issue by ksteczk** [soedinglab/MMseqs#1]
I tried to cluster a db with mmseqs_cluster by following a procedure form the user guide:
fasta2ffindex pdb70.fa pdb70
mmseqs_cluster pdb70 pdb20 tmp -cpu 24 --cascaded --id 0.2

The command:
ffindex2fasta pdb20 pdb20.fa
does not produce the fasta file. In the working directory I have files:
pdb70_h.index
pdb70_h
pdb70.index
pdb70
pdb20.index
pdb20

I think there is something wrong with pdb20 (the clustered db) that should be produced by mmseqs_cluster. pdb20 file does not contain fasta sequences (like pdb70) but PDB identifiers in my case (first 5 lines):
10mh_A
^@16vp_A
^@173d_C
^@1914_A
^@1a0a_A

ffindex2fasta pdb70 pdb70.fasta produces a nice fasta file.

**Comment by martin-steinegger** [comment]
The result database is stored as ffindex file. FFindex is an file indexing library. It needs two files an index file in your case the pdb20.index and a data file the pdb20. You can access single cluster compositions by using the tool ffindex_get pdb20 pdb20.index 10mh_A. Or use the ffindex2fasta to convert the ffindex file to a fasta file. 

Does this solve you problem?

**Comment by ksteczk** [comment]
No, it doesn't. The pdb20 data file, generated with mmseqs_cluster program,
does not contain sequence data but headers (due to some error in code?).
Therefore I am not able to extract fasta-formatted sequences by following
the procedure given by you. The clustering programming generates improper
data file.

Hope that helps in further investigations.
Kamil
26.11.2015 7:19 AM "Martin Steinegger" <notifications@github.com>
napisał(a):

**Comment by martin-steinegger** [comment]
The final output does not contain any sequence information. It is just the mapping of ids to clusters. 
There is a tool clusters2ffindex which converts a clusteing to fasta file with containing all sequences. 
It is called clusters2ffindex. ./cluster2ffindex pdb20 pdb70_h pdb70 pdb20.fasta

**Comment by ksteczk** [comment]
Thats'it! This is the step missing from the user guide! Thank you for the
explanation.
26.11.2015 8:41 AM "Martin Steinegger" <notifications@github.com>
napisał(a):

**Comment by martin-steinegger** [comment]
I should add this to the user guide. 
Can I close the issue?

**Comment by ksteczk** [comment]
I'm trying to verify the above procedure in following steps:
I have pdb70 fasta file. To cluster it down to 20% sequence identity I run:

fasta2ffindex pdb70.fa pdb70
mmseqs_cluster pdb70 pdb20 tmp -cpu 24 --cascaded --id 0.2

cluster2ffindex pdb20 pdb70_h pdb70 pdb20_fasta
ffindex2fasta pdb20_fasta pdb20.fst

The file pdb20.fst contains entries like this one (I've chosen the one with short sequence):
>173d_C
173d_C mol:protein length:11  ACTINOMYCIN D
TVPGVXTVPGV

How do I get the clustered fasta file then? I'd like to get one single fasta file containing all >20'000 sequences coming from this clustering. Am I missing something?

Thanks for your assistance; it's not so obvious how to use the software properly.

**Comment by ksteczk** [comment]
I run test for another database, nr database, and after cluster2ffindex followed by ffindex2fasta I got a file containing lines like these (these are three first lines of fasta file):
\>0406179A
gi|223020|prf||0406179A dismutase fragment,Cu/Zn superoxide
ATKAVCVLVWGSIKGLTEGLHGFGHQFGBBTAGCTSAGPHFNPLKHGGPKDEERSGDHCIIGRTLVVHEKADDLGKGGNEESTKTGNAGSRLACGVIGIAQ

How to get regular fasta file with proper headers then?

**Comment by martin-steinegger** [comment]
could you provide me the input file and the output file please?

**Comment by ksteczk** [comment]
I've sent them attached via e-mail.

**Comment by martin-steinegger** [comment]
I tested your pdb20 example. There was indeed an error in the cluster2ffindex script. 

Your output should look like this 

>0406179A
>gi|223020|prf||0406179A dismutase fragment,Cu/Zn superoxide
ATKAVCVLVWGSIKGLTEGLHGFGHQFGBBTAGCTSAGPHFNPLKHGGPKDEERSGDHCIIGRTLVVHEKADDLGKGGNEESTKTGNAGSRLACGVIGIAQ

I fixed it and pushed the bug fix to github. 
Please call 
  cd $MMDIR 
  git push 
and recompile the software. 

Sorry for the inconvenience.

Please try to cluster your db like this 

fasta2ffindex pdb70.fa pdb70
mkdir tmp
mmseqs_cluster pdb70 pdb20 tmp -cpu 24 --cascaded --id 0.2 -s 7
cluster2ffindex pdb20 pdb70_h pdb70 pdb20_fasta
ffindex2fasta pdb20_fasta pdb20.fst

The -s 7 parameter improves sensitivity of the method. 

The final output in pdb20.fst can be interpreted the following way 

>cluster1
>cluster1 sequence 1 (representative)
AASASAVASA
>cluster1 sequence 2 
AASASAVAAA
>cluster2
>cluster2 sequence 1 (representative)
VVVVVAAVAV
…

Thanks a lot for your feedback!

**Comment by ksteczk** [comment]
Thank you. It works now.

Sorry for the delay, we had some IT infrastructure migrations so I wasn't able to proceed with the clustering.
