### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ever4cyth** [soedinglab/MMseqs#3]
downloaded from github 2 days ago. compiled easily on ubuntu 14.04 but got error
fasta2ffindex short.fasta short
Segmentation fault (core dumped)

short.fasta looks like below. the same file works for kclust program. please let me know what info you need to troubleshoot. Thanks!

>DAG1_HUMAN
SIVVEWTNNTLPLEPCPKEQIAGLSRRIAEDDGKPRPAFSNALEPDFKATSITVTGSGSCRHLQFIPVVPPRRVPSEAPPTEVPDRDPEKSSEDD
>LRRN1_HUMAN
SIQNSECPQLCVCEIRPWFTPQSTYREATTVDCNDLRLTRIPSNLSSDTQVLLLQSNNIAKTVDELQQLFNLTELDFSQNNFTNIKEVGLANLTQLTTLHLEENQITEMTDYCLQDLSNLQELYINHNQISTISAHAFAGLKNLLRLHLNSNKLKVIDSRWFDSTPNLEILMIGENPVIGILDMNFKPLANLRSLVLAGMYLTDIPGNALVGLDSLESLSFYDNKLVKVPQLALQKVPNLKFLDLNKNPIHKIQEGDFKNMLRLKELGINNMGELVSVDRYALDNLPELTKLEATNNPKLSYIHRLAFRSVPALESLMLNNNALNAIYQKTVESLPNLREISIHSNPLRCDCVIHWINSNKTNIRFMEPLSMFCAMPPEYKGHQVKEVLIQDSSEQCLPMISHDSFPNRLNVDIGTTVFLDCRAMAEPEPEIYWVTPIGNKITVETLSDKYKLSSEGTLEISNIQIEDSGRYTCVAQNVQGADTRVATIKVNGTLLDGTQVLKIYVKQTESHSILVSWKVNSNVMTSNLKWSSATMKIDNPHITYTARVPVDVHEYNLTHLQPSTDYEVCLTVSNIHQQTQKSCVNVTTKNAAFAVDISDQETST
>NCTR2_HUMAN
QSKAQVLQSVAGQTLTVRCQYPPTGSLYEKKGWCKEASALVCIRLVTSSKPRTMAWTSRFTIWDDPDAGFFTVTMTDLREEDSGHYWCRIYRPSDNSVSKSVRFYLVVSPASASTQTSWTPRDLVSSQTQTQSCVPPTAGARQAPESPSTIPVPSQPQNSTLRPGPAAPI
>FCAR_HUMAN
QEGDFPMPFISAKSSPVIPLDGSVKIQCQAIREAYLTQLMIIKNSTYREIGRRLKFWNETDPEFVIDHMDANKAGRYQCQYRIGHYRFRYSDTLELVVTGLYGKPFLSADRGLVLMPGENISLTCSSAHIPFDRFSLAKEGELSLPQHQSGEHPANFSLGPVDLNVSGIYRCYGWYNRSPYLWSFPSNALELVVTDSIHQDYTTQ
>NTRI_HUMAN
MGVCGYLFLPWKCLVVVSLRLLFLVPTGVPVRSGDATFPKAMDNVTVRQGESATLRCTIDNRVTRVAWLNRSTILYAGNDKWCLDPRVVLLSNTQTQYSIEIQNVDVYDEGPYTCSVQTDNHPKTSRVHLIVQVSPKIVEISSDISINEGNNISLTCIATGRPEPTVTWRHISPKAVGFVSEDEYLEIQGITREQSGDYECSASNDVAAPVVRRVKVTVNYPPYISEAKGTGVPVGQKGTLQCEASAVPSAEFQWYKDDKRLIEGKKGVKVENRPFLSKLIFFNVSEHDYGNYTCVASNKLGHTNASIMLFGPGAVSEVSNGTSRRAGCVWLLPLLVLHLLLKF
>VPREB_HUMAN
MSWAPVLLMLFVYCTGCGPQPVLHQPPAMSSALGTTIRLTCTLRNDHDIGVYSVYWYQQRPGHPPRFLLRYFSQSDKSQGPQVPPRFSGSKDVARNRGYLSISELQPEDEAMYYCAMGARSSEKEEREREWEEEMEPTAARTRVP
>CD47_HUMAN
QLLFNKTKSVEFTFCNDTVVIPCFVTNMEAQNTTEVYVKWKFKGRDIYTFDGALNKSTVPTDFSSAKIEVSQLLKGDASLKMDKSDAVSHTGNYTCEVTELTREGETIIELKYRVVSWFSPN

**Comment by martin-steinegger** [comment]
I tried your example and it was running without any problems. 
Is this the whole file? Is there any id longer 31 bytes in a header? 

```
>DAG1_HUMAN
SIVVEWTNNTLPLEPCPKEQIAGLSRRIAEDDGKPRPAFSNALEPDFKATSITVTGSGSCRHLQFIPVVPPRRVPSEAPPTEVPDRDPEKSSEDD
>LRRN1_HUMAN
SIQNSECPQLCVCEIRPWFTPQSTYREATTVDCNDLRLTRIPSNLSSDTQVLLLQSNNIAKTVDELQQLFNLTELDFSQNNFTNIKEVGLANLTQLTTLHLEENQITEMTDYCLQDLSNLQELYINHNQISTISAHAFAGLKNLLRLHLNSNKLKVIDSRWFDSTPNLEILMIGENPVIGILDMNFKPLANLRSLVLAGMYLTDIPGNALVGLDSLESLSFYDNKLVKVPQLALQKVPNLKFLDLNKNPIHKIQEGDFKNMLRLKELGINNMGELVSVDRYALDNLPELTKLEATNNPKLSYIHRLAFRSVPALESLMLNNNALNAIYQKTVESLPNLREISIHSNPLRCDCVIHWINSNKTNIRFMEPLSMFCAMPPEYKGHQVKEVLIQDSSEQCLPMISHDSFPNRLNVDIGTTVFLDCRAMAEPEPEIYWVTPIGNKITVETLSDKYKLSSEGTLEISNIQIEDSGRYTCVAQNVQGADTRVATIKVNGTLLDGTQVLKIYVKQTESHSILVSWKVNSNVMTSNLKWSSATMKIDNPHITYTARVPVDVHEYNLTHLQPSTDYEVCLTVSNIHQQTQKSCVNVTTKNAAFAVDISDQETST
>NCTR2_HUMAN
QSKAQVLQSVAGQTLTVRCQYPPTGSLYEKKGWCKEASALVCIRLVTSSKPRTMAWTSRFTIWDDPDAGFFTVTMTDLREEDSGHYWCRIYRPSDNSVSKSVRFYLVVSPASASTQTSWTPRDLVSSQTQTQSCVPPTAGARQAPESPSTIPVPSQPQNSTLRPGPAAPI
>FCAR_HUMAN
QEGDFPMPFISAKSSPVIPLDGSVKIQCQAIREAYLTQLMIIKNSTYREIGRRLKFWNETDPEFVIDHMDANKAGRYQCQYRIGHYRFRYSDTLELVVTGLYGKPFLSADRGLVLMPGENISLTCSSAHIPFDRFSLAKEGELSLPQHQSGEHPANFSLGPVDLNVSGIYRCYGWYNRSPYLWSFPSNALELVVTDSIHQDYTTQ
>NTRI_HUMAN
MGVCGYLFLPWKCLVVVSLRLLFLVPTGVPVRSGDATFPKAMDNVTVRQGESATLRCTIDNRVTRVAWLNRSTILYAGNDKWCLDPRVVLLSNTQTQYSIEIQNVDVYDEGPYTCSVQTDNHPKTSRVHLIVQVSPKIVEISSDISINEGNNISLTCIATGRPEPTVTWRHISPKAVGFVSEDEYLEIQGITREQSGDYECSASNDVAAPVVRRVKVTVNYPPYISEAKGTGVPVGQKGTLQCEASAVPSAEFQWYKDDKRLIEGKKGVKVENRPFLSKLIFFNVSEHDYGNYTCVASNKLGHTNASIMLFGPGAVSEVSNGTSRRAGCVWLLPLLVLHLLLKF
>VPREB_HUMAN
MSWAPVLLMLFVYCTGCGPQPVLHQPPAMSSALGTTIRLTCTLRNDHDIGVYSVYWYQQRPGHPPRFLLRYFSQSDKSQGPQVPPRFSGSKDVARNRGYLSISELQPEDEAMYYCAMGARSSEKEEREREWEEEMEPTAARTRVP
>CD47_HUMAN
QLLFNKTKSVEFTFCNDTVVIPCFVTNMEAQNTTEVYVKWKFKGRDIYTFDGALNKSTVPTDFSSAKIEVSQLLKGDASLKMDKSDAVSHTGNYTCEVTELTREGETIIELKYRVVSWFSPN
```

**Comment by ever4cyth** [comment]
Thanks for your reply. I found what my problem is:

some sequences has a space between > and name, for example: > FCAR_human. After I changed to >FCAR_human. program runs.
