### ISSUE TITLE
line 18: 93954 Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ljcohen** [soedinglab/MMseqs#4]
I am running MMseqs on an hpc cluster on a 6-frame translated protein dataset with 84,559,379 sequences (21G). From the formula you provided, we did the following calculation:

M = (4*N*L + 8*a^k) byte
N = 84559379 or 85 million
L = 200
a = 20
k = 6
(4 * 85000000 * 200 + 8*20^6) = 
68512000000 bytes = 68.5 GB

I started the job on a node with 150 GB RAM but got a `Segmentation fault (core dumped)` message. Based on another open issue, I thought perhaps it did not have enough memory. So, I tried 400 GB and got the same result. Then, I tried 2 TB, again with the same result. At this point, I don't think it's a memory issue. 

Can you please tell me if there is another issue that could be causing the program to fail at this point (see error message below).

```
processed
...................................................................................................	84 Mio. sequences processed
.......................................................
Index table: init... from 0 to 84559379
Index table: fill...
/var/spool/torque/mom_priv/jobs/33427919.mgr-04.i.SC: line 18: 93954 Segmentation fault      (core dumped) mmseqs_cluster /mnt/scratch/ljcohen/peppy /mnt/scratch/ljcohen/peppy_clu_29 /mnt/scratch/ljcohen/tmp --cascaded -s 9
```

Here is the head of my data:

```
[ljcohen@dev-intel14 ljcohen]$ head all.pep 
>CAMNT_0016223697.0.0
LTSPHAYLRTSICQFGVVVATTITNRTTSGDPVPLVVDGGCGRTGYTLGSRGTISTCSASRMKMMMKMVMVMVMRKRGGTATSSSGMRKQWRIHWIRWGMHRCRTREDGSRNRNAGGTSAV
>CAMNT_0016223697.0.1
MQTAIPLFLPLFFYPLQITAMQRHQIMHETTSIRILIRSCPTGWCYWWRCWSGSSGDRVRNVRNTVPPHKYFLPNRTVDLQLCLMGVMLVSIISIISIIISSSSIIITTLIMYIF
>CAMNT_0016223697.3.0
IXXXXXXXXXXXXXFXXXXXXXXXXXXXXXXXXNXIXKXXXXXXXXXXXXXYXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXLXXXFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXIXXXLIXXXIXXXXIIXXXXXXXXXKXXXXXXXXXXXXXXXXXIXNIXIIXXXIXIXXXXXXXXXXXXXXXXXXXXXXXXKXXXXXXXKYXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXIXIXIXXXXXXIXXXXIXXIXXX
>CAMNT_0016223697.3.1
XXXXXXXXIXXXXXXXXXLXXXXXXXXXXXXXXXXXXXIXXXXFXXXXXXXXXXXXXXXXXXXLXXXXXXXXXXXXXXXXXXXXXNXXXXXXXXXXXXXXXIXXIXXIXXXXXXXXXXXIXXXXXXXXXXXXXXXXXXXXYXXXXXXLIXXXXXXXXXXXX
>CAMNT_0016223697.3.2
XXXXXXXXXXXXIXXXXXXXXXXXNIXXXXXXXIXIXXXXXXXIXXXXXXXXXXIXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXIXXXXXXXXXXXIXXXYXXXXXXXXXIXXXXXXXXXXIXXXXXIXIXXXXXXXXXXXXXXXXXXXXXXXXXXIXXXXXXIXXXFXIXXXXXXXXXXXXXXXXXXXXXXXXIXXXXXXXXXXXXXXX
```

**Comment by martin-steinegger** [comment]
I'm sure its not the memory limitation. 
Are there any characters in the sequences that are none alphanumeric?

**Comment by martin-steinegger** [comment]
We just released a binary for our user friendlier, faster, and more sensitive method MMseqs2.
It should be also more robust in handling user input.

https://github.com/soedinglab/MMseqs2
I would recommend you to use the new version instead.

**Comment by martin-steinegger** [comment]
Did not hear any feedback. I consider this solved. Please repost bug if it still occurs.
