### ISSUE TITLE
Is there any restart option available for mmseq cluster, failed after step 2: ALIGNMENT

### ISSUE THREAD

**Issue by narsapuramvijaykumar** [soedinglab/MMseqs#5]
I had submitted a dataset (28M) to the cluster on 16 cores with memory of 100GB. My command-line looks like
>>>mmseq_cluster dataset_DB dataset_DB_clu tmp/ --cascaded & (with some bsub args appended to it in front)
It was oke till  Step 2: PREFILTERING  then at  Step 2: ALIGNMENT it failed due to memory insufficient error (Total 7days till here)
  TERM_MEMLIMIT: job killed after reaching LSF memory usage limit.
Now I want to start the process from Step 2: ALIGNMENT till end(basically continue the process from where it had stopped). I have all db_pref* and db_aln* files in tmp directory.
When I am restarting the job it shows me --> tmp//db_pref_step1: File exists
Is there any way such that i can restart the process from where it had stopped..?
Or is  there any other way to handle 28M large data efficiently..?

**Comment by martin-steinegger** [comment]
--restart Restart the clustering workflow starting with alignment or clustering. The value is in the range [1:3]: 1: restart from prefiltering  2: from alignment; 3: from clustering.
--step          \t[int]\tRestart the step of the cascaded clustering. For values in [1:3], the resprective step 

So in your case it would be mmseq_cluster dataset_DB dataset_DB_clu tmp/ --cascaded --step 2 --restart 2. You have to delete the alignment results of step 2 first though. 

We just released a binary for our user friendlier, faster, and more sensitive method MMseqs2. 

https://github.com/soedinglab/MMseqs2
I would recommend you to use the new version instead.

**Comment by narsapuramvijaykumar** [comment]
Thanks for the inputs, It worked for me successfully..:)
I will be trying out the latest MMseq2 on newer datasets.
